#!/bin/bash
PROJECT_NAME=mala
PLATFORM=$1

# Exit on Any Command Failing
set -e
set -o pipefail

# Defining CI Build and Test Function
run_ci(){
  SRC_DIR=$1
  TOOLCHAIN_FILE=/opt/vcpkg/${PROJECT_NAME}/${PLATFORM}/scripts/buildsystems/vcpkg.cmake
  CHAINLOAD_FILE=/opt/jaystack/compiler/${PLATFORM}/etc/compiler.cmake
  BUILD_TYPE=$2
  cmake \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE \
    -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$CHAINLOAD_FILE \
    -DBUILD_TESTING=On \
    -DBUILD_DOC=Off \
    -DJAYSTACK_ENABLE_UBSAN=On \
    -DJAYSTACK_ENABLE_ASAN=On \
    -DJAYSTACK_ENABLE_ALL_WARNINGS=On \
    $SRC_DIR
  make -j8
  ctest
}


# Source Directory
echo "Source Directory is " $PWD
SRC=$PWD

# Push into Build Directory
mkdir -p /tmp/${PROJECT_NAME}/build
pushd /tmp/${PROJECT_NAME}/build

rm -rf *
run_ci $SRC Debug
rm -rf *
run_ci $SRC Release
